default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: harrogath

development:
  <<: *default
  database: flashcard_app_development

test:
  <<: *default
  database: flashcard_app_test

production:
  <<: *default
  database: flashcard_app_production
  url: <%= ENV['DATABASE_URL'] %>
